services:
  - type: web
    name: ocr-service
    env: python
    rootDir: ocr_service
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_PROJECT_ID
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false
      - key: GOOGLE_PRIVATE_KEY_ID
        sync: false
      - key: GOOGLE_CLIENT_EMAIL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
